GET http://localhost:80/api
Accept: application/json

###
GET http://localhost:80/api/member
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiNGYyNTMwZWI1YTEwMGMyN2FhYTRlM2JiNjVmOGM4YTJjOTUxNGUwYTFjZGIzNzM2MzFkMDY5MTczNTY5NmU1YzA3MmRjYWI1ZjUwMGFiNDciLCJpYXQiOjE1ODg2ODMxNTMsIm5iZiI6MTU4ODY4MzE1MywiZXhwIjoxNjIwMjE5MTUzLCJzdWIiOiIzIiwic2NvcGVzIjpbXX0.rJhxIB3NBWW5Eo2xLxNzwJTxj9K_X8TitxwSNyZhSRO3xNy1TwNm2ZfPifwo3IBrUDqQ22qYgnhZO-sQv71uvAfnW5CaJYQpxwePf9mhDOEkkLrbt7UfaQXLmL75LH7LaVT9h_FAZVykvKBl_bjMubLeom3JShTHffrvTVyTYl-zc1iPTq_1Orpk0ZHUfol4upI_AOsGYy0YMn4bQl22mkC5pFWC45eG10DwFs6dOdcR3_BLat0Pa9w0L15yZkaO8NEFAWj3tw_kSGLRudQuNL4CcmmSBAw171lXLKcfcj4rF4cthrh9DtStsQ8_xvgP6bRmyRPScfu1-Rw7hXRr5XvZ0PhlzpfW7NcTq0DIEGJG-XNOac3ny7dps-Coxsx4pW4dsg8nwDCv1kh7UmT6pOjY3jBelXO7ktlLHd-3HBXx3th5l8GfX2730DmDtt4Ph2x1O0uSUjwT6Hox3tR8QW1S_7c8WgKb-JwIrBizaJFdBKxKZchmEBG5lYrs2te1Sv_OtlwxYTcmodKR0JOVFkbCNI6YvE0ZTPGNftQyEi69Sf8RUkj-cBi4eAC5FdGU7KFezvX5yNjP0tXqBZmZ48rgtA62ylcOiH4lXQjV5L-EvZH6LAN8dRuyfV_vlbzK6r4SMynkPm_Ed4eODHHlCwHulMMWHJjFAV0HETs5pFI


###
PUT http://localhost/api/member
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiNDU3YzgwYzM0NTg1YjQ3NTQ4Y2E1MmY0NjY2NzQ1MWZkMjE3MmU3ZmViYzg5YzE5OTViZWMyYTJiZWU3ZmQxOTEzODYxNTUyNmM3ZDI3ZTIiLCJpYXQiOjE1ODg2NzM5ODIsIm5iZiI6MTU4ODY3Mzk4MiwiZXhwIjoxNjIwMjA5OTgyLCJzdWIiOiIzIiwic2NvcGVzIjpbXX0.cA7_32ln9J8b9T70lb1c3-9fka51ssvmSvKy_REqI-BiMhSyaj91vozPc3u0npEVB22a3XCahE_skF6cyrOIym0_TnrYOFW7nNHG90josF3-3n5qZvjGA0Mw9350zp5gMK2QeWRuYspQJ24-pZ6yp9ShSp-hyv_sTGtvNB1PiRU3vuKAfIJlNiyqG2HQhGetBxvrzYsXPqrHst6Ltl1VjEInelfpsb4iAD_R-guMzVz7m9NgmdCiteHTev427DL9f5U48ozraTJpMfbcBiTOb-ADgjTT9XZ9jHfLmqkaGPenW8aAui2sufUFOy5bjGWsi2WB29lupycp0F3qgkqk2q4m3gm5_EUbG_Lytdu_i_hKIqh5LmcUAP88vn-fMKRi4mbAfq06pwjdUi1_zQuiN2QQA9NJ_S4h6A1LOYOgc-vH0nVtT1QCUI69ZW2ArxaaNA_DLc1imWl6Equ1ETxCdHCaWJM4329eLUUrGe_tq_YVjI6kLfjURseydUlQrnf_uYAxm_A5-MZE2pJ1QEEW1I2vhLvMRI74_MOJ_Dl1kvs9i7bfIzQ1yhaltU81do4EScBGA9maxdZmNur100kmeyvSrreLYGgzZ9YEqtB0Rtb9BhcTtBQFrLBrSHXyFgPDzVRLccvfECo_c-ayBZaqgZGARFxh-vlmM3GM7WL7ZtA

{
    "id" : 3,
    "name" : "test",
    "email": " test@test.com",
    "cardinal_numeral": "12"
}


###
GET http://localhost:80/api/user
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiNDU3YzgwYzM0NTg1YjQ3NTQ4Y2E1MmY0NjY2NzQ1MWZkMjE3MmU3ZmViYzg5YzE5OTViZWMyYTJiZWU3ZmQxOTEzODYxNTUyNmM3ZDI3ZTIiLCJpYXQiOjE1ODg2NzM5ODIsIm5iZiI6MTU4ODY3Mzk4MiwiZXhwIjoxNjIwMjA5OTgyLCJzdWIiOiIzIiwic2NvcGVzIjpbXX0.cA7_32ln9J8b9T70lb1c3-9fka51ssvmSvKy_REqI-BiMhSyaj91vozPc3u0npEVB22a3XCahE_skF6cyrOIym0_TnrYOFW7nNHG90josF3-3n5qZvjGA0Mw9350zp5gMK2QeWRuYspQJ24-pZ6yp9ShSp-hyv_sTGtvNB1PiRU3vuKAfIJlNiyqG2HQhGetBxvrzYsXPqrHst6Ltl1VjEInelfpsb4iAD_R-guMzVz7m9NgmdCiteHTev427DL9f5U48ozraTJpMfbcBiTOb-ADgjTT9XZ9jHfLmqkaGPenW8aAui2sufUFOy5bjGWsi2WB29lupycp0F3qgkqk2q4m3gm5_EUbG_Lytdu_i_hKIqh5LmcUAP88vn-fMKRi4mbAfq06pwjdUi1_zQuiN2QQA9NJ_S4h6A1LOYOgc-vH0nVtT1QCUI69ZW2ArxaaNA_DLc1imWl6Equ1ETxCdHCaWJM4329eLUUrGe_tq_YVjI6kLfjURseydUlQrnf_uYAxm_A5-MZE2pJ1QEEW1I2vhLvMRI74_MOJ_Dl1kvs9i7bfIzQ1yhaltU81do4EScBGA9maxdZmNur100kmeyvSrreLYGgzZ9YEqtB0Rtb9BhcTtBQFrLBrSHXyFgPDzVRLccvfECo_c-ayBZaqgZGARFxh-vlmM3GM7WL7ZtA

###
POST http://localhost/oauth/token
Content-Type: application/json

{
    "grant_type" : "password",
    "client_id" : "2",
    "client_secret" : "zRcUPcEgciqwQRjwyvwjYWbXrzba9NBUziapmDaO",
    "username" : "test@test.com",
    "password" : "123456",
    "scope" : ""
}
###
